import React, { useState, useCallback, useRef, useEffect } from "react";
import { FileVideo, Upload, Loader2, Download, Languages, FileText, Play, Pause, Type, Palette, Layout as LayoutIcon, Sparkles, Save } from "lucide-react";
import { useDropzone } from "react-dropzone";
import { motion, AnimatePresence } from "framer-motion";
import { useSearchParams, useNavigate } from "react-router-dom";
import { cn } from "../lib/utils";
import { processVideoSubtitles } from "../services/subtitleService";
import { db } from "../lib/firebase";
import { doc, getDoc, updateDoc } from "firebase/firestore";

type SubtitleStyle = 'karaoke' | 'tiktok' | 'typewriter' | 'neon';

interface Subtitle {
  id: number;
  start: string;
  end: string;
  text: string;
  startTimeSeconds: number;
  endTimeSeconds: number;
}

export function VideoEditorScreen() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const projectId = searchParams.get("id");

  const [project, setProject] = useState<any>(null);
  const [file, setFile] = useState<File | null>(null);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [subtitles, setSubtitles] = useState<Subtitle[]>([]);
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [selectedStyle, setSelectedStyle] = useState<SubtitleStyle>('tiktok');
  const [syncOffset, setSyncOffset] = useState(0);
  
  const videoRef = useRef<HTMLVideoElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    if (projectId && projectId !== "null") {
      const fetchProject = async () => {
        try {
          const docRef = doc(db, "projects", projectId);
          const docSnap = await getDoc(docRef);
          if (docSnap.exists()) {
            setProject(docSnap.data());
            if (docSnap.data().subtitles) {
              setSubtitles(docSnap.data().subtitles);
            }
          }
        } catch (error) {
          console.error("Error fetching project:", error);
        }
      };
      fetchProject();
    }
  }, [projectId]);

  const onDrop = useCallback((acceptedFiles: File[]) => {
    console.log("Files dropped:", acceptedFiles);
    if (acceptedFiles.length > 0) {
      const selectedFile = acceptedFiles[0];
      setFile(selectedFile);
      
      try {
        const url = URL.createObjectURL(selectedFile);
        setVideoUrl(url);
        console.log("Video URL created successfully:", url);
      } catch (err) {
        console.error("Error creating object URL:", err);
        alert("Erro ao processar o arquivo de vídeo localmente.");
      }
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    onDropRejected: (fileRejections) => {
      console.log("Files rejected:", fileRejections);
      const error = fileRejections[0]?.errors[0]?.message;
      alert(`Arquivo rejeitado: ${error || "Formato não suportado"}. Por favor, use MP4, MOV ou WebM.`);
    },
    accept: { 
      'video/*': ['.mp4', '.mov', '.avi', '.webm', '.mpeg', '.mpg', '.ogv', '.3gp']
    },
    multiple: false
  });

  const handleProcess = async () => {
    if (!project?.audioUrl) return alert("Gere uma música primeiro!");
    setIsProcessing(true);
    try {
      // In a real app, we'd transcribe the audio generated by IA
      const data = await processVideoSubtitles(project.audioUrl) as any;
      
      const timeToSeconds = (timeStr: string) => {
        const [hms, mmm] = timeStr.replace('.', ',').split(',');
        const [h, m, s] = hms.split(':').map(Number);
        return h * 3600 + m * 60 + s + (Number(mmm) || 0) / 1000;
      };

      const processedSubtitles = data.subtitles.map((s: any) => ({
        ...s,
        startTimeSeconds: timeToSeconds(s.start),
        endTimeSeconds: timeToSeconds(s.end)
      }));
      
      setSubtitles(processedSubtitles);
      
      // Save to Firestore
      if (projectId) {
        await updateDoc(doc(db, "projects", projectId), {
          subtitles: processedSubtitles,
          status: "subtitles_ready"
        });
      }
    } catch (error) {
      console.error(error);
      alert("Erro ao sincronizar legendas.");
    } finally {
      setIsProcessing(false);
    }
  };

  useEffect(() => {
    return () => {
      if (videoUrl) URL.revokeObjectURL(videoUrl);
    };
  }, [videoUrl]);

  const handleVideoError = (e: any) => {
    const videoElement = e.target as HTMLVideoElement;
    console.error("Video load error:", videoElement.error);
    alert(`Erro ao carregar o vídeo: ${videoElement.error?.message || "O formato pode não ser suportado pelo seu navegador"}. Tente converter para MP4.`);
    setVideoUrl(null);
    setFile(null);
  };

  const togglePlay = () => {
    if (videoRef.current && audioRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
        audioRef.current.pause();
      } else {
        videoRef.current.play();
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  useEffect(() => {
    const interval = setInterval(() => {
      if (videoRef.current && !videoRef.current.paused) {
        setCurrentTime(videoRef.current.currentTime);
      }
    }, 50);
    return () => clearInterval(interval);
  }, []);

  const currentSubtitle = subtitles.find(
    s => (currentTime + syncOffset) >= s.startTimeSeconds && (currentTime + syncOffset) <= s.endTimeSeconds
  );

  const getStyleClasses = () => {
    switch (selectedStyle) {
      case 'karaoke':
        return "text-white font-black drop-shadow-[0_4px_0_rgba(168,85,247,1)] uppercase italic tracking-tighter";
      case 'tiktok':
        return "bg-yellow-400 text-black px-4 py-1 font-black uppercase italic transform -rotate-1";
      case 'typewriter':
        return "text-cyan-400 font-mono font-bold border-r-4 border-cyan-400 animate-pulse";
      case 'neon':
        return "text-cyan-400 font-bold drop-shadow-[0_0_15px_rgba(6,182,212,0.8)] tracking-[0.2em] uppercase";
      default:
        return "text-white font-bold";
    }
  };

  const handleExport = async () => {
    if (!file || !project?.audioUrl || subtitles.length === 0) {
      return alert("Certifique-se de ter um vídeo, áudio e legendas sincronizadas!");
    }
    
    setIsProcessing(true);
    const formData = new FormData();
    formData.append("video", file);
    formData.append("audioUrl", project.audioUrl);
    formData.append("subtitles", JSON.stringify(subtitles));
    formData.append("style", selectedStyle);

    try {
      const response = await fetch("/api/export", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) throw new Error("Export failed");
      
      const data = await response.json();
      navigate(`/export?id=${projectId}&videoUrl=${encodeURIComponent(data.videoUrl)}`);
    } catch (error) {
      console.error(error);
      alert("Erro ao exportar vídeo.");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 pb-32">
      {!projectId && (
        <div className="mb-8 p-6 bg-yellow-500/10 border border-yellow-500/20 rounded-3xl flex items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-yellow-500/20 rounded-2xl flex items-center justify-center text-yellow-500">
              <Sparkles size={24} />
            </div>
            <div>
              <h4 className="text-white font-black uppercase italic tracking-tight">Nenhum projeto ativo</h4>
              <p className="text-zinc-500 text-xs font-medium">Você precisa gerar uma música primeiro para usar os recursos de IA.</p>
            </div>
          </div>
          <button 
            onClick={() => navigate("/generate-music")}
            className="px-6 py-3 bg-yellow-500 text-black rounded-xl font-black uppercase tracking-widest text-[10px] hover:scale-105 transition-all"
          >
            Gerar Música
          </button>
        </div>
      )}
      <div className="flex flex-col lg:flex-row gap-8">
        {/* Preview Area */}
        <div className="flex-1 space-y-6">
          <div className="relative aspect-video bg-black rounded-[3rem] overflow-hidden border border-white/10 shadow-[0_0_50px_rgba(0,0,0,0.5)] group">
            {videoUrl ? (
              <>
                <video 
                  key={videoUrl || 'no-video'}
                  ref={videoRef}
                  src={videoUrl}
                  className="w-full h-full object-cover"
                  muted
                  playsInline
                  onError={handleVideoError}
                />
                {project?.audioUrl && <audio ref={audioRef} src={project.audioUrl} />}
                
                {/* Subtitle Overlay */}
                <AnimatePresence mode="wait">
                  {currentSubtitle && (
                    <motion.div 
                      key={currentSubtitle.id}
                      initial={{ opacity: 0, scale: 0.8, y: 20 }}
                      animate={{ opacity: 1, scale: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 1.1, y: -20 }}
                      className="absolute inset-0 flex items-center justify-center pointer-events-none px-12 text-center"
                    >
                      <span className={cn("text-4xl md:text-6xl transition-all duration-300", getStyleClasses())}>
                        {currentSubtitle.text}
                      </span>
                    </motion.div>
                  )}
                </AnimatePresence>

                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <button 
                    onClick={togglePlay}
                    className="w-24 h-24 bg-white/10 backdrop-blur-2xl rounded-full flex items-center justify-center text-white hover:scale-110 transition-transform"
                  >
                    {isPlaying ? <Pause size={48} fill="currentColor" /> : <Play size={48} fill="currentColor" className="ml-2" />}
                  </button>
                </div>
              </>
            ) : (
              <div 
                {...getRootProps()} 
                className={cn(
                  "w-full h-full flex flex-col items-center justify-center text-center p-12 cursor-pointer transition-all bg-zinc-900/50",
                  isDragActive ? "bg-cyan-500/5" : "hover:bg-white/5"
                )}
              >
                <input {...getInputProps()} />
                <div className="w-24 h-24 bg-zinc-800 rounded-3xl flex items-center justify-center mb-6 transform rotate-3 group-hover:rotate-0 transition-transform">
                  <Upload className="text-cyan-500" size={40} />
                </div>
                <h2 className="text-3xl font-black text-white uppercase italic tracking-tighter mb-2">Importar Vídeo</h2>
                <p className="text-zinc-500 max-w-xs font-medium mb-6">Arraste seu clipe ou clique no botão abaixo para começar.</p>
                <button type="button" className="px-8 py-3 bg-white/10 hover:bg-white/20 border border-white/10 rounded-xl text-white text-xs font-black uppercase tracking-widest transition-all">
                  Selecionar Arquivo
                </button>
              </div>
            )}
          </div>

          {/* Timeline */}
          <div className="bg-zinc-900/50 border border-white/5 rounded-[2rem] p-6 space-y-4">
            <div className="flex items-center gap-4">
              <span className="text-[10px] font-black text-zinc-600 uppercase tracking-widest w-12">00:00</span>
              <div className="flex-1 h-3 bg-zinc-800 rounded-full relative overflow-hidden">
                <motion.div 
                  className="absolute top-0 left-0 h-full bg-gradient-to-r from-cyan-500 to-blue-500"
                  style={{ width: `${(currentTime / (videoRef.current?.duration || 1)) * 100}%` }}
                />
                {/* Beat markers (mock) */}
                <div className="absolute inset-0 flex justify-around opacity-20">
                  {[...Array(20)].map((_, i) => <div key={i} className="w-px h-full bg-white" />)}
                </div>
              </div>
              <span className="text-[10px] font-black text-zinc-600 uppercase tracking-widest w-12">
                {Math.floor(currentTime / 60)}:{(currentTime % 60).toFixed(0).padStart(2, '0')}
              </span>
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="w-full lg:w-80 space-y-6">
          <div className="bg-zinc-900/50 border border-white/5 rounded-[2.5rem] p-8 space-y-8">
            <div className="space-y-4">
              <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500 flex items-center gap-2">
                <Palette size={14} /> Estilo Visual
              </h3>
              <div className="grid grid-cols-2 gap-2">
                {(['karaoke', 'tiktok', 'typewriter', 'neon'] as SubtitleStyle[]).map((s) => (
                  <button
                    key={s}
                    onClick={() => setSelectedStyle(s)}
                    className={cn(
                      "py-3 rounded-xl text-[9px] font-black uppercase tracking-widest border transition-all",
                      selectedStyle === s 
                        ? "bg-white text-black border-white" 
                        : "bg-zinc-800 text-zinc-500 border-transparent hover:border-white/10"
                    )}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>

            <div className="space-y-4">
              <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500 flex items-center gap-2">
                <LayoutIcon size={14} /> Sincronização
              </h3>
              <input 
                type="range" 
                min="-2" 
                max="2" 
                step="0.05"
                value={syncOffset} 
                onChange={(e) => setSyncOffset(Number(e.target.value))}
                className="w-full h-1 bg-zinc-800 rounded-lg appearance-none cursor-pointer accent-cyan-500"
              />
              <div className="flex justify-between text-[9px] font-black text-zinc-600 uppercase">
                <span>Atrasar</span>
                <span className="text-white">{syncOffset.toFixed(2)}s</span>
                <span>Adiantar</span>
              </div>
            </div>

            <div className="pt-6 border-t border-white/5 space-y-3">
              <button
                onClick={() => navigate(`/subtitle-editor?id=${projectId}`)}
                className="w-full bg-zinc-800 text-zinc-400 py-4 rounded-2xl font-black uppercase tracking-widest italic flex items-center justify-center gap-2 hover:text-white hover:bg-zinc-700 transition-all"
              >
                <FileText size={20} /> Editar Letras Manualmente
              </button>

              <button
                onClick={handleProcess}
                disabled={isProcessing || !videoUrl}
                className="w-full bg-cyan-500 text-white py-4 rounded-2xl font-black uppercase tracking-widest italic flex items-center justify-center gap-2 hover:scale-[1.02] active:scale-[0.98] transition-all disabled:opacity-50 shadow-[0_0_30px_rgba(6,182,212,0.3)]"
              >
                {isProcessing ? <Loader2 className="animate-spin" size={20} /> : <Sparkles size={20} />}
                {isProcessing ? "Sincronizando..." : "Auto-Sync Letras"}
              </button>
              
              <button
                onClick={handleExport}
                disabled={subtitles.length === 0 || isProcessing}
                className="w-full bg-white text-black py-4 rounded-2xl font-black uppercase tracking-widest italic flex items-center justify-center gap-2 hover:scale-[1.02] active:scale-[0.98] transition-all disabled:opacity-50"
              >
                {isProcessing ? <Loader2 className="animate-spin" size={20} /> : <Download size={20} />}
                {isProcessing ? "Processando..." : "Exportar Vídeo"}
              </button>
            </div>
          </div>

          {/* Subtitle List Preview */}
          {subtitles.length > 0 && (
            <div className="bg-zinc-900/50 border border-white/5 rounded-[2.5rem] p-6 max-h-64 overflow-y-auto custom-scrollbar">
              <div className="space-y-2">
                {subtitles.map(s => (
                  <div 
                    key={s.id}
                    className={cn(
                      "p-3 rounded-xl text-[10px] font-bold transition-all",
                      currentTime >= s.startTimeSeconds && currentTime <= s.endTimeSeconds
                        ? "bg-cyan-500/20 text-cyan-400 border border-cyan-500/30"
                        : "text-zinc-600"
                    )}
                  >
                    {s.text}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
